name: Jest Tests and Coverage Check

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: package-lock.json

      - name: Purge all caches
        run: |
          npm cache clean --force
          rm -rf node_modules package-lock.json
          rm -rf ~/.npm ~/.yarn

      - name: Clean install
        run: |
          rm -rf node_modules
          npm ci

      - name: Run Jest tests
        run: npm test -- --coverage

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
