name: Publish Extension

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for creating releases
      id-token: write # For OIDC auth with VS Code Marketplace

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Verify version bump
        run: |
          TAG_VERSION="${GITHUB_REF#refs/tags/v}"
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          git checkout HEAD~1 -- package.json 2>/dev/null || true
          PREVIOUS_VERSION=$(node -p "require('./package.json').version" || echo "null")

          echo "Tag Version: $TAG_VERSION"
          echo "Current Version: $CURRENT_VERSION"
          echo "Previous Version: $PREVIOUS_VERSION"

          if [[ "$CURRENT_VERSION" == "$TAG_VERSION" ]]; then
            echo "::error::Version not updated in package.json"
            exit 1
          fi

      - name: Install dependencies
        run: |
          npm install
          npm install -g @vscode/vsce

      - name: Package Extension
        run: |
          mkdir -p dist
          vsce package --out ./dist/extension-${{ github.ref_name }}.vsix

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: ${{ github.ref_name }}
          body: 'VS Code extension release'
          files: |
            dist/extension-${{ github.ref_name }}.vsix
          draft: true
          prerelease: false

      - name: Validate Token + Extension
        run: |
          # Skip if OIDC (no PAT available)
          if [[ -z "$VSCE_PAT" ]]; then
            echo "Using OIDC - token test not possible in dry-run"
          else
            echo "Testing PAT..."
            vsce show mac-ecooptimizers.ecooptimizer || echo "Token valid (extension may not exist)"
          fi

          # Always test packaging
          vsce publish -p $VSCE_PAT
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
