name: PR Version Check

on:
  pull_request:
    branches: [main]

jobs:
  validate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0 # Required for branch comparison

      - name: Get PR version
        id: pr_version
        run: |
          PR_VERSION=$(node -p "require('./package.json').version")
          echo "pr_version=$PR_VERSION" >> $GITHUB_OUTPUT

      - name: Fetch main branch
        run: git fetch origin main

      - name: Get main's version
        id: main_version
        run: |
          MAIN_VERSION=$(git show origin/main:package.json | node -p "JSON.parse(require('fs').readFileSync(0)).version")
          echo "main_version=$MAIN_VERSION" >> $GITHUB_OUTPUT

      - name: Validate version bump
        run: |
          # Install compare-versions tool
          npm install compare-versions

          echo "PR Version: ${{ steps.pr_version.outputs.pr_version }}"
          echo "Main Version: ${{ steps.main_version.outputs.main_version }}"

          if ! npx compare-versions "${{ steps.pr_version.outputs.pr_version }}" "${{ steps.main_version.outputs.main_version }}"; then
            echo "::error::Version must be higher than main (${{ steps.main_version.outputs.main_version }})"
            exit 1
          fi

          if [[ "${{ steps.pr_version.outputs.pr_version }}" == "${{ steps.main_version.outputs.main_version }}" ]]; then
            echo "::error::Version unchanged from main"
            exit 1
          fi

          echo "✓ Version validated"
